### ISSUE TITLE
get_list_targets() invalid return property: self._pipewire_list_currently_using is never assigned

### ISSUE THREAD

**Issue by mrteathyme** [pablodz/pipewire_python#10]
# Expected Behavior

On calling get_list_targets i expect to be provided a dictionary of Node id's and their respective device names.

# Current Behavior

pipewire_list_currently_using property does not exist causing the function to return an exception rather than the expected data.

# Failure Information (for bugs)

AttributeError: 'Controller' object has no attribute '_pipewire_list_currently_using'

## Steps to Reproduce

call Controller.get_list_targets()

**Comment by pablodz** [comment]
New version deployed  v0.0.96
